CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE ROLE platform_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD 'platform-test-migrator-password';
CREATE ROLE platform_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS CONNECTION LIMIT 10 PASSWORD 'platform-test-app-password';
CREATE ROLE temporal LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD 'temporal-test-password';
CREATE ROLE keycloak LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD 'keycloak-test-password';

CREATE DATABASE temporal OWNER temporal;
CREATE DATABASE temporal_visibility OWNER temporal;
CREATE DATABASE keycloak OWNER keycloak;

CREATE SCHEMA platform AUTHORIZATION platform_migrator;
CREATE SCHEMA identity AUTHORIZATION platform_migrator;
CREATE SCHEMA crm AUTHORIZATION platform_migrator;
GRANT USAGE ON SCHEMA platform, identity, crm TO platform_app;
