FROM quay.io/keycloak/keycloak:26.8.0
COPY docker/integration/keycloak-realm.json /opt/keycloak/data/import/platform-realm.json
EXPOSE 8080 9000
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm", "--http-host=0.0.0.0", "--http-port=8080"]
