#!/usr/bin/env sh
set -eu
compose='docker compose -f docker/integration/compose.yml'

$compose exec -T postgres psql -U platform_migrator -d platform -v ON_ERROR_STOP=1 -f - < tests/integration/fixtures.sql
PGPASSWORD=platform-test-app-password $compose exec -T --env PGPASSWORD postgres psql -U platform_app -d platform -v ON_ERROR_STOP=1 -f - < tests/integration/rls.sql
PGPASSWORD=platform-test-app-password $compose exec -T --env PGPASSWORD postgres psql -U platform_app -d platform -v ON_ERROR_STOP=1 -f - < tests/integration/commerce-rls.sql

$compose exec -T postgres psql -U platform_migrator -d platform -Atqc "SELECT to_regclass('integrations.connections'), to_regclass('integrations.webhook_subscriptions'), to_regclass('integrations.provider_actions'), to_regclass('policy.approval_requests'), to_regclass('messaging.conversations'), to_regclass('messaging.messages'), to_regclass('messaging.message_attachments'), to_regclass('messaging.media_uploads'), to_regclass('messaging.templates'), to_regclass('tickets.records'), to_regclass('tickets.comments'), to_regclass('commerce.stores'), to_regclass('commerce.products'), to_regclass('commerce.variants'), to_regclass('commerce.inventory_levels'), to_regclass('commerce.orders'), to_regclass('commerce.order_lines'), to_regclass('commerce.payments'), to_regclass('commerce.fulfillments'), to_regclass('commerce.provider_mappings'), to_regclass('commerce.order_timeline'), to_regprocedure('integrations.resolve_webhook_connection(text,uuid)'), to_regprocedure('integrations.claim_webhook_deliveries(text,integer,integer)'), to_regprocedure('integrations.claim_sync_runs(text,integer,integer)'), to_regprocedure('integrations.claim_webhook_subscriptions(text,integer,integer)'), to_regprocedure('integrations.claim_provider_actions(text,integer,integer)'), to_regprocedure('messaging.claim_outbound_messages(text,integer,integer)');" | grep -qx 'integrations.connections|integrations.webhook_subscriptions|integrations.provider_actions|policy.approval_requests|messaging.conversations|messaging.messages|messaging.message_attachments|messaging.media_uploads|messaging.templates|tickets.records|tickets.comments|commerce.stores|commerce.products|commerce.variants|commerce.inventory_levels|commerce.orders|commerce.order_lines|commerce.payments|commerce.fulfillments|commerce.provider_mappings|commerce.order_timeline|integrations.resolve_webhook_connection(text,uuid)|integrations.claim_webhook_deliveries(text,integer,integer)|integrations.claim_sync_runs(text,integer,integer)|integrations.claim_webhook_subscriptions(text,integer,integer)|integrations.claim_provider_actions(text,integer,integer)|messaging.claim_outbound_messages(text,integer,integer)'
